import { boolean, date, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone:true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone:true }).defaultNow().notNull() };
export const roleEnum = pgEnum("role", ["platform_admin","general_manager","client","operations_supervisor","driller","control","tenant_owner","admin","supervisor","operator","viewer"]);
export const billingCycleEnum = pgEnum("billing_cycle", ["monthly","annual"]);
export const sourceEnum = pgEnum("measurement_source", ["manual","imported","sensor"]);

export const tenants = pgTable("tenants", { id:uuid("id").defaultRandom().primaryKey(), name:text("name").notNull(), slug:text("slug").notNull(), currency:text("currency").default("USD").notNull(), active:boolean("active").default(true).notNull(), settings:jsonb("settings").default({}), ...timestamps }, t => [uniqueIndex("tenant_slug_idx").on(t.slug)]);
export const users = pgTable("users", { id:uuid("id").defaultRandom().primaryKey(), email:text("email").notNull(), name:text("name").notNull(), passwordHash:text("password_hash").notNull(), platformAdmin:boolean("platform_admin").default(false).notNull(), ...timestamps }, t => [uniqueIndex("user_email_idx").on(t.email)]);
export const memberships = pgTable("memberships", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id,{onDelete:"cascade"}).notNull(), userId:uuid("user_id").references(()=>users.id,{onDelete:"cascade"}).notNull(), role:roleEnum("role").notNull(), ...timestamps }, t => [index("membership_tenant_idx").on(t.tenantId), uniqueIndex("membership_unique_idx").on(t.tenantId,t.userId)]);
export const sites = pgTable("sites", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), name:text("name").notNull(), location:text("location"), ...timestamps }, t=>[index("site_tenant_idx").on(t.tenantId)]);
export const projects = pgTable("projects", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), siteId:uuid("site_id").references(()=>sites.id), name:text("name").notNull(), code:text("code").notNull(), status:text("status").notNull(), ...timestamps }, t=>[index("project_tenant_idx").on(t.tenantId)]);
export const rigs = pgTable("rigs", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), siteId:uuid("site_id").references(()=>sites.id), manufacturer:text("manufacturer").notNull(), model:text("model").notNull(), serial:text("serial").notNull(), code:text("code").notNull(), hourlyCost:numeric("hourly_operational_cost",{precision:12,scale:2}), capabilities:jsonb("measurement_capabilities").default({}), active:boolean("active").default(true), notes:text("notes"), ...timestamps }, t=>[index("rig_tenant_idx").on(t.tenantId),index("rig_site_idx").on(t.siteId)]);
export const drillholes = pgTable("drillholes", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), projectId:uuid("project_id").references(()=>projects.id).notNull(), rigId:uuid("rig_id").references(()=>rigs.id), code:text("code").notNull(), targetDepth:numeric("target_depth",{precision:10,scale:2}), currentDepth:numeric("current_depth",{precision:10,scale:2}).default("0"), diameter:text("diameter").notNull(), status:text("status").notNull(), startDate:date("start_date"), estimatedFinish:date("estimated_finish_date"), notes:text("notes"), ...timestamps }, t=>[index("drillhole_tenant_idx").on(t.tenantId),index("drillhole_project_idx").on(t.projectId),index("drillhole_rig_idx").on(t.rigId)]);
export const shifts = pgTable("shifts", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), drillholeId:uuid("drillhole_id").references(()=>drillholes.id).notNull(), rigId:uuid("rig_id").references(()=>rigs.id).notNull(), date:date("date").notNull(), shiftType:text("shift_type").notNull(), crew:text("crew"), depthStart:numeric("depth_start"), depthEnd:numeric("depth_end"), effectiveHours:numeric("effective_drilling_hours"), totalHours:numeric("total_shift_hours").default("12"), timeBreakdown:jsonb("time_breakdown").default({}), notes:text("notes"), ...timestamps }, t=>[index("shift_tenant_date_idx").on(t.tenantId,t.date),index("shift_drillhole_idx").on(t.drillholeId)]);
export const bitProducts = pgTable("bit_products", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), manufacturer:text("manufacturer").notNull(), brand:text("brand"), productName:text("product_name").notNull(), matrix:text("matrix_code").notNull(), diameter:text("diameter").notNull(), purchasePrice:numeric("purchase_price"), currency:text("currency").default("USD"), active:boolean("active").default(true), ...timestamps }, t=>[index("bit_product_tenant_idx").on(t.tenantId)]);
export const bitRuns = pgTable("bit_runs", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), drillholeId:uuid("drillhole_id").references(()=>drillholes.id).notNull(), rigId:uuid("rig_id").references(()=>rigs.id).notNull(), bitProductId:uuid("bit_product_id").references(()=>bitProducts.id).notNull(), entryDepth:numeric("entry_depth").notNull(), exitDepth:numeric("exit_depth"), drillingHours:numeric("drilling_hours"), purchaseCost:numeric("purchase_cost"), wearLevel:integer("wear_level"), removalReason:text("removal_reason"), legacyCostMetric:numeric("legacy_cost_metric"), legacyFormula:text("legacy_formula"), ...timestamps }, t=>[index("bit_run_tenant_idx").on(t.tenantId),index("bit_run_drillhole_idx").on(t.drillholeId)]);
export const intervals = pgTable("drilling_intervals", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), shiftId:uuid("shift_id").references(()=>shifts.id).notNull(), drillholeId:uuid("drillhole_id").references(()=>drillholes.id).notNull(), rigId:uuid("rig_id").references(()=>rigs.id).notNull(), bitRunId:uuid("bit_run_id").references(()=>bitRuns.id), startDepth:numeric("start_depth",{precision:10,scale:2}).notNull(), endDepth:numeric("end_depth",{precision:10,scale:2}).notNull(), drillingMinutes:numeric("drilling_minutes").notNull(), pressure:numeric("pressure_value"), torque:numeric("torque_value"), rpm:numeric("rpm"), waterFlow:numeric("water_flow"), waterReturn:text("water_return"), coreRecovery:numeric("core_recovery_pct"), hardness:integer("operational_hardness"), fracturing:text("fracturing"), abrasivity:text("abrasivity"), vibration:text("vibration"), stability:text("stability"), comment:text("comment"), source:sourceEnum("source").default("manual"), measuredAt:timestamp("measured_at",{withTimezone:true}), ...timestamps }, t=>[index("interval_tenant_depth_idx").on(t.tenantId,t.startDepth,t.endDepth),index("interval_drillhole_idx").on(t.drillholeId),index("interval_rig_idx").on(t.rigId),index("interval_bit_run_idx").on(t.bitRunId)]);
export const inventory = pgTable("inventory", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), siteId:uuid("site_id").references(()=>sites.id), bitProductId:uuid("bit_product_id").references(()=>bitProducts.id).notNull(), quantityOnHand:integer("quantity_on_hand").default(0), reservedQuantity:integer("reserved_quantity").default(0), reorderLevel:integer("reorder_level").default(0), unitCost:numeric("unit_cost"), status:text("status").notNull(), ...timestamps }, t=>[index("inventory_tenant_idx").on(t.tenantId)]);
export const plans = pgTable("plans", { id:uuid("id").defaultRandom().primaryKey(), name:text("name").notNull(), monthlyPrice:numeric("monthly_price"), annualPrice:numeric("annual_price"), minimumCommitmentMonths:integer("minimum_commitment_months").default(1).notNull(), limits:jsonb("limits").notNull(), active:boolean("active").default(true), ...timestamps });
export const subscriptions = pgTable("subscriptions", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), planId:uuid("plan_id").references(()=>plans.id).notNull(), billingCycle:billingCycleEnum("billing_cycle").notNull(), status:text("status").notNull(), startsAt:timestamp("starts_at",{withTimezone:true}).notNull(), renewsAt:timestamp("renews_at",{withTimezone:true}), trialEnd:timestamp("trial_end",{withTimezone:true}), provider:text("provider").default("demo"), externalSubscriptionId:text("external_subscription_id"), ...timestamps }, t=>[index("subscription_tenant_idx").on(t.tenantId)]);
export const featureFlags = pgTable("feature_flags", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), key:text("key").notNull(), enabled:boolean("enabled").default(false).notNull(), ...timestamps }, t=>[uniqueIndex("flag_tenant_key_idx").on(t.tenantId,t.key)]);
export const recommendations = pgTable("recommendations", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), drillholeId:uuid("drillhole_id").references(()=>drillholes.id).notNull(), input:jsonb("input").notNull(), result:jsonb("result").notNull(), selectedBitId:uuid("selected_bit_id").references(()=>bitProducts.id), decision:text("decision"), reason:text("reason"), createdBy:uuid("created_by").references(()=>users.id), ...timestamps }, t=>[index("recommendation_tenant_idx").on(t.tenantId)]);
export const surveys = pgTable("surveys", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), drillholeId:uuid("drillhole_id").references(()=>drillholes.id).notNull(), measuredDepth:numeric("measured_depth").notNull(), inclination:numeric("inclination").notNull(), azimuth:numeric("azimuth").notNull(), source:sourceEnum("source").default("imported"), ...timestamps }, t=>[index("survey_drillhole_depth_idx").on(t.drillholeId,t.measuredDepth)]);
export const importJobs = pgTable("import_jobs", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id).notNull(), status:text("status").notNull(), fileName:text("file_name").notNull(), type:text("type").notNull(), rowsTotal:integer("rows_total").default(0), rowsImported:integer("rows_imported").default(0), rowsSkipped:integer("rows_skipped").default(0), errors:jsonb("errors").default([]), createdBy:uuid("created_by").references(()=>users.id), ...timestamps }, t=>[index("import_tenant_idx").on(t.tenantId)]);
export const auditLogs = pgTable("audit_logs", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id), userId:uuid("user_id").references(()=>users.id), action:text("action").notNull(), entity:text("entity").notNull(), entityId:uuid("entity_id"), metadata:jsonb("metadata").default({}), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[index("audit_tenant_idx").on(t.tenantId)]);
export const manualRecords = pgTable("manual_records", { id:uuid("id").defaultRandom().primaryKey(), tenantId:uuid("tenant_id").references(()=>tenants.id,{onDelete:"cascade"}).notNull(), kind:text("kind").notNull(), payload:jsonb("payload").notNull(), createdByEmail:text("created_by_email").notNull(), ...timestamps }, t=>[index("manual_record_tenant_kind_idx").on(t.tenantId,t.kind),index("manual_record_created_idx").on(t.createdAt)]);
